#General Data
name: Reserve
version: 0.1.5.4
description: A set of APIs for unison across Bukkit Plugins.
author: creatorfromhell
api-version: 1.20

#Plugin Data
main: net.tnemc.core.Reserve
load: STARTUP
softdepend: [ Vault ]
